[
  {
    "Name": "Redirect_Found",
    "Enabled": true,
    "Scanner": 2,
    "Author": "@six2dez1",
    "Payloads": [],
    "Encoder": [],
    "UrlEncode": false,
    "CharsToUrlEncode": "",
    "Grep": [
      "true,Or,?next\u003d",
      "true,Or,?url\u003d",
      "true,Or,?target\u003d",
      "true,Or,?rurl\u003d",
      "true,Or,?dest\u003d",
      "true,Or,?destination\u003d",
      "true,Or,?redir\u003d",
      "true,Or,?redirect_uri\u003d",
      "true,Or,?redirect_url\u003d",
      "true,Or,?redirect\u003d",
      "true,Or,/redirect/",
      "true,Or,/cgi-bin/redirect.cgi?",
      "true,Or,/out/",
      "true,Or,/out?",
      "true,Or,?view\u003d",
      "true,Or,/login?to\u003d",
      "true,Or,?image_url\u003d",
      "true,Or,?go\u003d",
      "true,Or,?return\u003d",
      "true,Or,?returnTo\u003d",
      "true,Or,?return_to\u003d",
      "true,Or,?checkout_url\u003d",
      "true,Or,?continue\u003d",
      "true,Or,?return_path\u003d"
    ],
    "Tags": [
      "All"
    ],
    "PayloadResponse": false,
    "NotResponse": false,
    "TimeOut1": "",
    "TimeOut2": "",
    "isTime": false,
    "contentLength": "",
    "iscontentLength": false,
    "CaseSensitive": false,
    "ExcludeHTTP": false,
    "OnlyHTTP": false,
    "IsContentType": true,
    "ContentType": "text/css,image/jpeg,image/png,image/svg+xml,image/gif,image/tiff,image/webp,image/x-icon,application/font-woff,image/vnd.microsoft.icon,font/ttf,font/woff2",
    "HttpResponseCode": "",
    "NegativeCT": true,
    "IsResponseCode": false,
    "ResponseCode": "",
    "NegativeRC": false,
    "urlextension": "",
    "isurlextension": false,
    "NegativeUrlExtension": false,
    "MatchType": 1,
    "Scope": 0,
    "RedirType": 0,
    "MaxRedir": 0,
    "payloadPosition": 0,
    "payloadsFile": "",
    "grepsFile": "",
    "IssueName": "Possible Redirect Found",
    "IssueSeverity": "Information",
    "IssueConfidence": "Certain",
    "IssueDetail": "Possible  Redirect Found",
    "RemediationDetail": "Redirect Found",
    "IssueBackground": "Possible Redirect Found",
    "RemediationBackground": "Redirect Found",
    "Header": [],
    "VariationAttributes": [],
    "InsertionPointType": [],
    "Scanas": false,
    "Scantype": 0,
    "pathDiscovery": false
  }
]